#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

imwheel --kill &
sxhkd &
nitrogen --restore &
picom -f --experimental-backend &
$HOME/.config/polybar/launch.sh

bspc monitor DP-4 -d 4 5 6
bspc monitor DP-2 -d 7 8 9
bspc monitor DP-0 -d 1 2 3

bspc config border_width	2
bspc config window_gap		5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a rdesktop state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
